CC = gcc
ASM = nasm
LD = ld

CFLAGS = -m32 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -fno-pie -nostdlib -Wall -Wextra

ASMFLAGS = -f elf32
LDFLAGS = -m elf_i386 -T linker.ld

SRC_C := $(shell find kernel Drivers Lib Networking -name '*.c' 2>/dev/null)
SRC_NASM := $(shell find kernel Drivers boot -name '*.asm' 2>/dev/null)
SRC_GAS := $(shell find kernel Drivers boot -name '*.s' -not -path 'boot/boot.s' 2>/dev/null)

OBJS := boot/boot.o $(SRC_C:.c=.o) $(SRC_NASM:.asm=.o) $(SRC_GAS:.s=.o)


all: kernel.elf iso

kernel.elf: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.asm
	$(ASM) $(ASMFLAGS) $< -o $@

%.o: %.s
	$(ASM) $(ASMFLAGS) $< -o $@

iso: kernel.elf
	mkdir -p iso/boot/grub
	cp kernel.elf iso/boot/kernel.elf
	cp boot/grub.cfg iso/boot/grub/grub.cfg
	grub-mkrescue -o aevrosos.iso iso/

clean:
	rm -f $(OBJS) kernel.elf iso/boot/kernel.elf aevrosos.iso
	rm -rf iso

.PHONY: all iso clean