SHELL := /usr/bin/env bash
CC = gcc
ASM = nasm
LD = ld

CFLAGS = -m32 -ffreestanding -fno-builtin -fno-stack-protector \
         -nostdlib -nostdinc -fno-pic -fno-pie \
         -fno-asynchronous-unwind-tables \
         -fno-exceptions -fno-rttiASMFLAGS = -f elf32
		 
LDFLAGS = -m elf_i386 -T linker.ld

C_SRCS := $(shell find kernel -type f -name '*.c' | sort)
ASM_SRCS := $(shell find kernel boot -type f \( -name '*.asm' -o -name '*.s' \) ! -name 'boot.s' | sort)

C_OBJS := $(C_SRCS:.c=.o)
ASM_OBJS := $(ASM_SRCS:.asm=.o)
ASM_OBJS := $(ASM_OBJS:.s=.o)

KERNEL_OBJS := boot/boot.o $(C_OBJS) $(ASM_OBJS)

all: kernel.elf

kernel.elf: $(KERNEL_OBJS)
	$(LD) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.asm
	$(ASM) $(ASMFLAGS) $< -o $@

%.o: %.s
	$(ASM) $(ASMFLAGS) $< -o $@

iso: kernel.elf
	mkdir -p iso/boot/grub
	cp kernel.elf iso/boot/kernel.elf
	cp boot/grub.cfg iso/boot/grub/grub.cfg
	grub-mkrescue -o forgeos.iso iso/

clean:
	rm -rf *.o kernel.elf iso forgeos.iso build_tmp
